// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CircularBuffer`, `MobileMetrics`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `push_to_usb`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `push`

String? pollConfig() => RustLib.instance.api.crateApiPollConfig();

/// Returns the current USB connection state as a string.
/// Dart polls this to detect disconnection even if the Android broadcast is missed.
String getConnectionState() =>
    RustLib.instance.api.crateApiGetConnectionState();

Future<String> getMobileMetrics() =>
    RustLib.instance.api.crateApiGetMobileMetrics();

/// Start the USB streaming pipeline using the Android-provided AOA file descriptor.
/// This is called from Dart when the Android framework detects USB accessory attachment
/// and passes the native file descriptor through the MethodChannel.
Future<String> startUsbStreaming({required int fd}) =>
    RustLib.instance.api.crateApiStartUsbStreaming(fd: fd);

/// Legacy AOA handshake — kept for reference but not used on Android
/// (Android framework handles AOA negotiation, not the app)
Future<String> startAoa() => RustLib.instance.api.crateApiStartAoa();

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiGreet(name: name);
